config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  root 'pages#home'

  resources :shape_calculators
  resources :sentence_generators
  resources :guess_the_numbers
  resources :users

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/shape_calculator.rb
class ShapeCalculator < ApplicationRecord
end

app/controllers/shape_calculators_controller.rb
class ShapeCalculatorsController < ApplicationController
  before_action :set_shape_calculator, only: [:show, :edit, :update, :destroy]

  # POST /shape_calculators
  # POST /shape_calculators.json
  def create
    if !logged_in?
      format.json { render json: {status: 'error'}}
    end
    @shape_calculator = ShapeCalculator.new(shape_calculator_params)
    @shape_calculator.user_id = current_user.id

    respond_to do |format|
      if @shape_calculator.save
        format.html { redirect_to @shape_calculator, notice: 'Shape calculator was successfully created.' }
        format.json { render :show, status: :created, location: @shape_calculator }
      else
        format.html { render :new }
        format.json { render json: @shape_calculator.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shape_calculator
      @shape_calculator = ShapeCalculator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shape_calculator_params
      params.require(:shape_calculator).permit(:shape, :area)
    end
end

app/helpers/shape_calculators_helper.rb
module ShapeCalculatorsHelper
end

app/views/shape_calculators/_form.html.erb
<%= form_for(shape_calculator) do |f| %>
  <% if shape_calculator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shape_calculator.errors.count, "error") %> prohibited this shape_calculator from being saved:</h2>

      <ul>
      <% shape_calculator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shape %>
    <%= f.text_field :shape %>
  </div>

  <div class="field">
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shape_calculators/edit.html.erb
<h1>Editing Shape Calculator</h1>

<%= render 'form', shape_calculator: @shape_calculator %>

<%= link_to 'Show', @shape_calculator %> |
<%= link_to 'Back', shape_calculators_path %>

app/views/shape_calculators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shape Calculators</h1>

<table>
  <thead>
    <tr>
      <th>Shape</th>
      <th>Area</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shape_calculators.each do |shape_calculator| %>
      <tr>
        <td><%= shape_calculator.shape %></td>
        <td><%= shape_calculator.area %></td>
        <td><%= shape_calculator.user_id %></td>
        <td><%= link_to 'Show', shape_calculator %></td>
        <td><%= link_to 'Edit', edit_shape_calculator_path(shape_calculator) %></td>
        <td><%= link_to 'Destroy', shape_calculator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shape Calculator', new_shape_calculator_path %>

app/views/shape_calculators/new.html.erb
<h1>New Shape Calculator</h1>

<%= render 'form', shape_calculator: @shape_calculator %>

<%= link_to 'Back', shape_calculators_path %>

app/views/shape_calculators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shape:</strong>
  <%= @shape_calculator.shape %>
</p>

<p>
  <strong>Area:</strong>
  <%= @shape_calculator.area %>
</p>

<p>
  <strong>User:</strong>
  <%= @shape_calculator.user_id %>
</p>

<%= link_to 'Edit', edit_shape_calculator_path(@shape_calculator) %> |
<%= link_to 'Back', shape_calculators_path %>