config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  root 'pages#home'

  resources :shape_calculators
  resources :sentence_generators
  resources :guess_the_numbers
  resources :users

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/guess_the_number.rb
class GuessTheNumber < ApplicationRecord
  belongs_to :user
  validates :tries, numericality: {greater_than: -1},
                    presence: true
  validates :number, presence: true
end

app/controllers/guess_the_numbers_controller.rb
class GuessTheNumbersController < ApplicationController
  before_action :set_guess_the_number, only: [:show, :edit, :update, :destroy]

  # GET /guess_the_numbers
  # GET /guess_the_numbers.json
  def index
    @guess_the_numbers = GuessTheNumber.all
  end

  # GET /guess_the_numbers/1
  # GET /guess_the_numbers/1.json
  def show
  end

  # POST /guess_the_numbers
  # POST /guess_the_numbers.json
  def create
    if !logged_in?
      format.json { render json: {status: 'error'}}
    end
    @guess_the_number = GuessTheNumber.new
    @guess_the_number.tries = 0
    @guess_the_number.user_id = current_user.id
    @guess_the_number.number = rand 1000 # todo this should go in a config variable
    respond_to do |format|
      if @guess_the_number.save
        format.html { redirect_to @guess_the_number, notice: 'Guess the number was successfully created.' }
        format.json { render :show, status: :created, location: @guess_the_number }
      else
        format.html { render :new }
        format.json { render json: @guess_the_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guess_the_numbers/1
  # PATCH/PUT /guess_the_numbers/1.json
  def update
    respond_to do |format|
      guess_the_number = GuessTheNumber.find params[:id]
      guess_the_number.tries += 1;
      from_db = guess_the_number.number
      from_req = params[:guess_the_number][:number].to_i
      if from_db < from_req
        status = 'higher'
      elsif from_db > from_req
        status = 'lower'
      else
        status = 'ok'
      end

      if guess_the_number.save
        format.html { redirect_to @guess_the_number, notice: 'Guess the number was successfully updated.' }
        format.json { render json: { status: status } }
      else
        format.html { render :edit }
        format.json { render json: @guess_the_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guess_the_numbers/1
  # DELETE /guess_the_numbers/1.json
  def destroy
    @guess_the_number.destroy
    respond_to do |format|
      format.html { redirect_to guess_the_numbers_url, notice: 'Guess the number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guess_the_number
      @guess_the_number = GuessTheNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guess_the_number_params
      params.require(:guess_the_number).permit(:tries, :number, :user_id)
    end
end

app/helpers/guess_the_numbers_helper.rb
module GuessTheNumbersHelper
end

app/views/guess_the_numbers/_form.html.erb
<%= form_for(guess_the_number) do |f| %>
  <% if guess_the_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guess_the_number.errors.count, "error") %> prohibited this guess_the_number from being saved:</h2>

      <ul>
      <% guess_the_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tries %>
    <%= f.number_field :tries %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guess_the_numbers/edit.html.erb
<h1>Editing Guess The Number</h1>

<%= render 'form', guess_the_number: @guess_the_number %>

<%= link_to 'Show', @guess_the_number %> |
<%= link_to 'Back', guess_the_numbers_path %>

app/views/guess_the_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guess The Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Tries</th>
      <th>Number</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guess_the_numbers.each do |guess_the_number| %>
      <tr>
        <td><%= guess_the_number.tries %></td>
        <td><%= guess_the_number.number %></td>
        <td><%= guess_the_number.user_id %></td>
        <td><%= link_to 'Show', guess_the_number %></td>
        <td><%= link_to 'Edit', edit_guess_the_number_path(guess_the_number) %></td>
        <td><%= link_to 'Destroy', guess_the_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guess The Number', new_guess_the_number_path %>

app/views/guess_the_numbers/new.html.erb
<h1>New Guess The Number</h1>

<%= render 'form', guess_the_number: @guess_the_number %>

<%= link_to 'Back', guess_the_numbers_path %>

app/views/guess_the_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tries:</strong>
  <%= @guess_the_number.tries %>
</p>

<p>
  <strong>Number:</strong>
  <%= @guess_the_number.number %>
</p>

<p>
  <strong>User:</strong>
  <%= @guess_the_number.user_id %>
</p>

<%= link_to 'Edit', edit_guess_the_number_path(@guess_the_number) %> |
<%= link_to 'Back', guess_the_numbers_path %>